[[updates.cli]]
package-ecosystem = "cargo"
[[updates.cli.ignore]]
dependency-name = "kittycad-modeling-cmds"

[[updates."kittycad.rs"]]
package-ecosystem = "cargo"
[[updates."kittycad.rs".ignore]]
dependency-name = "kittycad-modeling-cmds"
